### ISSUE TITLE
Consider implementing the Serde traits using from_reader

### ISSUE THREAD

**Issue by aignas** [Danaozhong/rust-zserio#66]
A placeholder for future ideas.

Using something like https://docs.rs/serde_json/latest/serde_json/fn.from_reader.html should be possible in theory.

**Comment by wichert** [comment]
We can support something like `zserio::read_from(reader)` pretty easily. I'm not sure if any traits from `serde` itself are useful. I was thinking of doing this as part of a fix for #75.
