### ISSUE TITLE
Split into two packages

### ISSUE THREAD

**Issue by wichert** [Danaozhong/rust-zserio#80]
Currently the zserio compiler and the runtime library are both part of the same crate. I suggest splitting those into two packages:
`zserio` with just the runtime, and `zserio-compiler` with the compiler. We can keep them in the same repository

**Comment by Danaozhong** [comment]
Thank you for raising this idea. I am supportive of this, and appreciate any PR :) Otherwise, I can put it in the backlog of my features to develop.

**Comment by wichert** [comment]
Doing a split probably means we will end up with two packages and three crates:

* `zserio` package containing the runtime code (`ztype`, `from_*`, `to_*` and the `Error` types)
* `zsero-compiler` package, containing a library crate with support code (currently `rust_zserio::internal`) and the binary crate with the command line tool

My proposal is to create a new `/crates` folder for these two packages. For `zserio-compiler` we'll also need to introduce a small public API that can be used in `build.rs` files.

@Danaozhong if you are happy with this proposal I can whip up a PR over the next week.
